#!/bin/bash

# Get the dir of this file
FILE="$( cd "$(dirname "$0")" ; pwd -P )"
COMPOSEFILE=$FILE/docker-compose.yml

echo ""
echo "=========================================================================="
echo " _____                     ____        _ "
echo "|   __|___ ___ _ _ ___ ___|    \ ___ _| |"
echo "|__   | -_|  _| | | -_|  _|  |  | .'| . |"
echo "|_____|___|_|  \_/|___|_| |____/|__,|___|"
echo ""
echo "While we wait let me tell you a joke: "
echo ""
curl -H 'Accept: text/plain' https://icanhazdadjoke.com/
echo ""
echo ""
echo "=========================================================================="
echo ""

# Check if docker is installed before we do a lot of docker things
if ! dpkg -s docker &> /dev/null
then
        sudo apt install docker docker-compose -y
fi

# Check for env file
$FILE/scripts/setupScript

# Main Execution Loop
while [ "$1" != "" ]
do
	case $1 in
		-r | --run )
			shift
			$FILE/scripts/startContainer $COMPOSEFILE $1
			shift
		;;
		-s | --stop )
			shift
			$FILE/scripts/stopContainer $COMPOSEFILE $1
			shift
		;;
		-u | --update )
			shift
			$FILE/scripts/updateContainer $COMPOSEFILE $1
			shift
		;;
		-ps | --show )
			shift
			$FILE/scripts/statusContainer $COMPOSEFILE $1
			shift
		;;
		-b | --backup )
			shift
			$FILE/scripts/backupContainer $FILE
			shift
		;;
		-sy | --sync )
			shift
			$FILE/scripts/syncData $FILE
			shift
		;;
	esac
done
