#!/bin/bash

# Establishing the root DIR for the application.
# Everything else uses this to make there directories so this is very important
export DIR="$( cd "$(dirname "$0")" ; pwd -P )"

# Loads the default Variables for direcotries like APPDIR
. ./config.sh

# Prints the Serverdad log and a joke from the icanhazdadjokes api
. ./serverdad-logo.sh

# Check if docker is installed before we do a lot of docker things
if ! dpkg -s docker &> /dev/null
then
        sudo apt install docker docker-compose -y
fi

if [ ! -f "$DIR/.env" ]
then
	$SETUP/envCreation.sh
else
	# Main Execution Loop
	while [ "$1" != "" ]
	do
		case $1 in
			container )
				shift
				# Figure out what machine command
				case $1 in
					-r | --run )
						shift
						$CONTAINER/start.sh $1
					;;
					-s | --stop )
		        			shift
		        			$CONTAINER/stop.sh $1
					;;
					-u | --update )
			            		shift
	        		    		$CONTAINER/update.sh $1
					;;
					* )
						shift
						echo "No or incorrect argument passed to container command"
					;;
				esac
			;;
			machine )
				shift
				case $1 in
					-u | --update )
						shift
						#update machine
						$MACHINE/update.sh
					;;
					-s | --sleep )
						shift
						#sleep machine
						$MACHINE/sleep.sh
					;;
					* )
						shift
						echo "No or incorrect arument passed to machine command"
					;;
				esac
			;;
			ps )
				shift
				$SCRIPTS/status.sh $1
				shift
			;;
			exec )
				shift
				$SCRIPTS/exec.sh $1
				shift
			;;
			init )
				shift
				$SCRIPTS/initilize.sh
				shift
			;;
			backup )
				shift
				$SCRIPTS/backup.sh
				shift
			;;
			restore )
				shift
				$SCRIPTS/restore.sh
				shift
			;;
			sync )
				shift
				$SCRIPTS/sync.sh
				shift
			;;
			logs )
				shift
				$SCRIPTS/logs.sh $@
				shift
			;;
			* )
				shift
				echo "No arguments passed in"
			;;
		esac
	shift
	done
fi

echo ""
